name: Build Filters/Scriptlets
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - docs/**
      - scripts/build-third-party-filters.ts
  pull_request: null
jobs:
  build:
    name: Build Filters/Scriptlets
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          check-latest: true
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install
      - run: pnpm run build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: SukkaLab/filters.cdn.skk.moe
          publish_branch: master
          cname: filters.cdn.skk.moe
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: public
          keep_files: true
